'use client';
import { SyntheticEvent, useState } from 'react';
import { ArrowDownRight, ArrowRight, Check, ChevronRight, Menu, X, Workflow, Blocks, Cable, Headphones, AppWindow, Languages } from 'lucide-react';

type Lang='en'|'th';
const logo='/icon-192.png';
function Image({src,alt,width,height,className}:{src:string,alt:string,width:number,height:number,className?:string,sizes?:string}){return <img src={src} alt={alt} width={width} height={height} className={className} loading={src===logo?'eager':'lazy'}/>}
const copy={
  en:{
    nav:['Home','Problem First','Solutions','Portfolio','About','Contact'], talk:'Talk to Us',
    heroTag:'Software solutions / Technology partner', heroTitle:<>From Zero<br/>to <em>Solution.</em></>, heroText:'We begin with the business problem—not a preferred technology. Then we design software that makes the work simpler, clearer, and ready to scale.', explore:'Explore our work', proof:['ZERO ASSUMPTIONS','BUILT FOR REAL WORK'],
    problemTag:'Problem first. Always.', problemTitle:<>Before we write code,<br/><em>we read the work.</em></>, problemText:'Most software problems are not really software problems. They are disconnected steps, repeated data entry, unclear ownership, and information trapped between people and tools.', problemClose:'We map the reality first. Then we remove friction with the smallest system that can create meaningful change.', problems:[['01','Observe','How work actually moves—not how it is supposed to.'],['02','Find the friction','Where time, data, and responsibility fall between tools.'],['03','Define the outcome','What should become faster, clearer, or more dependable.'],['04','Build the system','Only then do we choose the right architecture and technology.']],
    solutionsTag:'Capabilities', solutionsTitle:<>One partner.<br/>The whole system.</>, solutionsText:'Strategy, design, engineering, integration, and long-term care—connected by one understanding of your business.',
    portfolioTag:'Selected work / 01', portfolioTitle:'CondoMate', portfolioSub:'Condominium Management System', portfolioText:'A real operational platform for condominium management teams and residents. CondoMate brings maintenance, parcels, shared-space booking, announcements, finance, accounts, and reporting into one connected workflow.', live:'Live product environment', resident:'Resident experience', management:'Management console', portfolioCta:'Discuss a similar system', portfolioNote:'Real product screens from the Punna Residence 5 implementation. No concept renders.',
    gallery:[['Resident dashboard','A focused home for announcements, parcels, maintenance, and daily tasks.'],['Maintenance workflow','Residents submit, track, and review repair requests in one place.'],['Shared-space booking','Clear availability, capacity checks, and time-slot requests.']],
    processTag:'How we work', processTitle:<>Zero assumptions.<br/>Five clear stages.</>, processText:'We do not begin with a predetermined technology. A clear five-stage process helps us discover, shape, and deliver the solution that fits your business.',
    aboutTag:'CeroSoft / Technology partner', aboutTitle:<>Technology should solve problems,<br/><em>not create new ones.</em></>, aboutText:'CeroSoft combines software engineering with an understanding of business operations. We translate complex workflows into systems that people can actually use, maintain, and trust.', mission:'Make technology simpler and more accessible through practical software that solves real-world problems.', vision:'Become the trusted technology partner for businesses seeking practical and sustainable digital systems.',
    legacyTag:'A familiar starting point', legacyTitle:'Excel. Chats. Paper. Repeated entry.', legacyText:'Fragmented tools are often a sign that the business has outgrown its current workflow—not that the team is doing something wrong.', legacyCta:'Tell us what is not working',
    contactTag:'Start from zero', contactTitle:<>Bring us the problem.<br/><em>We’ll find the path.</em></>, contactText:'You do not need a technical specification. Show us how the work happens today and what needs to improve.', next:'We listen first, map the workflow, and recommend a practical next step.', fields:['Name','Company / Organization','Email','Phone','What do you want to improve?','Message'], send:'Start a Conversation', success:'Thank you. Your details are ready; delivery will be connected when the CeroSoft contact API is available.', footer:'Simple Software. Real Solutions.'
  },
  th:{
    nav:['หน้าแรก','เริ่มจากปัญหา','โซลูชัน','ผลงาน','เกี่ยวกับเรา','ติดต่อ'], talk:'คุยกับเรา',
    heroTag:'Software Solutions / Technology Partner', heroTitle:<>เริ่มจากศูนย์<br/>สร้างเป็น<em>โซลูชัน</em></>, heroText:'เราเริ่มจากปัญหาของธุรกิจ ไม่ใช่จากเทคโนโลยี เราทำความเข้าใจปัญหาและวิธีการทำงานของคุณ ก่อนออกแบบซอฟต์แวร์ที่ช่วยให้งานง่ายขึ้น เป็นระบบมากขึ้น และพร้อมรองรับการเติบโตในอนาคต', explore:'ดูผลงานของเรา', proof:['เริ่มจากความเข้าใจจริง','สร้างเพื่อการทำงานจริง'],
    problemTag:'เริ่มจากปัญหาเสมอ', problemTitle:<>ก่อนเขียนโค้ด<br/><em>เราศึกษาวิธีทำงาน</em></>, problemText:'ปัญหาซอฟต์แวร์ส่วนใหญ่ไม่ใช่เรื่องซอฟต์แวร์ แต่คือขั้นตอนที่ไม่เชื่อมกัน การกรอกข้อมูลซ้ำ ความรับผิดชอบที่ไม่ชัดเจน และข้อมูลที่กระจายอยู่หลายเครื่องมือ', problemClose:'เราเข้าใจหน้างานและมองหาจุดติดขัดก่อน แล้วจึงสร้างระบบที่พอดีและสร้างผลลัพธ์ได้จริง', problems:[['01','สังเกต','ดูว่างานเกิดขึ้นจริงอย่างไร ไม่ใช่แค่ควรเป็นอย่างไร'],['02','ค้นหาจุดติดขัด','หาจุดที่เวลา ข้อมูล และความรับผิดชอบหล่นหายระหว่างเครื่องมือ'],['03','กำหนดผลลัพธ์','ระบุว่าสิ่งใดควรเร็วขึ้น ชัดขึ้น หรือเชื่อถือได้มากขึ้น'],['04','สร้างระบบ','จากนั้นจึงเลือกสถาปัตยกรรมและเทคโนโลยีที่เหมาะสม']],
    solutionsTag:'ความสามารถ', solutionsTitle:<>พาร์ตเนอร์หนึ่งเดียว<br/>ดูแลทั้งระบบ</>, solutionsText:'ตั้งแต่กลยุทธ์ ออกแบบ พัฒนา เชื่อมต่อ ไปจนถึงดูแลระยะยาว ด้วยความเข้าใจธุรกิจเดียวกันตลอดโครงการ',
    portfolioTag:'ผลงานที่คัดสรร / 01', portfolioTitle:'CondoMate', portfolioSub:'ระบบบริหารจัดการคอนโดมิเนียม', portfolioText:'แพลตฟอร์มใช้งานจริงสำหรับนิติบุคคลและลูกบ้าน เชื่อมงานแจ้งซ่อม พัสดุ จองพื้นที่ส่วนกลาง ประกาศ การเงิน บัญชี และรายงานไว้ใน workflow เดียว', live:'ระบบที่ใช้งานจริง', resident:'ประสบการณ์ลูกบ้าน', management:'ระบบบริหารนิติบุคคล', portfolioCta:'คุยเรื่องระบบลักษณะนี้', portfolioNote:'ภาพจากระบบจริงของ Punna Residence 5 ไม่ใช่ภาพจำลอง',
    gallery:[['แดชบอร์ดลูกบ้าน','ศูนย์กลางประกาศ พัสดุ แจ้งซ่อม และงานประจำวัน'],['กระบวนการแจ้งซ่อม','แจ้ง ติดตาม และตรวจสอบสถานะงานซ่อมได้ในที่เดียว'],['การจองพื้นที่ส่วนกลาง','ตรวจสอบจำนวนผู้ใช้ ความจุ และช่วงเวลาได้อย่างชัดเจน']],
    processTag:'วิธีทำงาน', processTitle:<>ไม่ยึดติดกับคำตอบเดิม<br/>เดินหน้าอย่างเป็นขั้นตอน</>, processText:'เราไม่เริ่มต้นด้วยการคิดไว้ก่อนว่าต้องใช้เทคโนโลยีอะไร แต่ใช้กระบวนการทำงาน 5 ขั้นตอนที่ชัดเจน เพื่อค้นหาและพัฒนาโซลูชันที่เหมาะกับธุรกิจของคุณจริง ๆ',
    aboutTag:'CeroSoft / Technology Partner', aboutTitle:<>เทคโนโลยีควรแก้ปัญหา<br/><em>ไม่ใช่สร้างปัญหาใหม่</em></>, aboutText:'CeroSoft ผสานวิศวกรรมซอฟต์แวร์กับความเข้าใจกระบวนการธุรกิจ เพื่อเปลี่ยน workflow ที่ซับซ้อนให้เป็นระบบที่ใช้งานจริง ดูแลต่อได้ และไว้วางใจได้', mission:'ทำให้เทคโนโลยีง่ายและเข้าถึงได้ ด้วยซอฟต์แวร์ที่ใช้งานได้จริงและแก้ปัญหาจริง', vision:'เป็นพาร์ตเนอร์ด้านเทคโนโลยีที่ธุรกิจไว้วางใจ สำหรับระบบดิจิทัลที่ใช้งานได้จริงและยั่งยืน',
    legacyTag:'จุดเริ่มต้นที่คุ้นเคย', legacyTitle:'Excel แชต กระดาษ และการกรอกซ้ำ', legacyText:'เครื่องมือที่กระจัดกระจายมักเป็นสัญญาณว่าธุรกิจเติบโตเกิน workflow เดิมแล้ว ไม่ใช่ความผิดของทีมงาน', legacyCta:'เล่าให้เราฟังว่าอะไรยังไม่เวิร์ก',
    contactTag:'เริ่มจากศูนย์', contactTitle:<>นำปัญหามาคุยกัน<br/><em>เราจะช่วยหาเส้นทาง</em></>, contactText:'คุณไม่จำเป็นต้องมีเอกสารสเปก แค่เล่าว่าวันนี้งานเกิดขึ้นอย่างไร และอยากให้อะไรดีขึ้น', next:'เราจะฟังก่อน ทำความเข้าใจ workflow และเสนอขั้นตอนถัดไปที่เหมาะสม', fields:['ชื่อ','บริษัท / องค์กร','อีเมล','โทรศัพท์','สิ่งที่ต้องการปรับปรุง','รายละเอียด'], send:'เริ่มต้นพูดคุย', success:'ขอบคุณค่ะ ข้อมูลพร้อมแล้ว ระบบจัดส่งจะเชื่อมต่อเมื่อ Contact API ของ CeroSoft พร้อมใช้งาน', footer:'ซอฟต์แวร์ที่เรียบง่าย โซลูชันที่ใช้ได้จริง'
  }
};
const services=[AppWindow,Workflow,Blocks,Cable,Headphones];
const serviceText={en:[['Custom Software','Web applications and internal systems built around the way your team works.'],['Business Automation','Reduce repeated work and turn manual steps into clear workflows.'],['Web Solutions','Corporate sites, portals, and online services with purpose and clarity.'],['System Integration','Connect APIs, databases, existing tools, and operational data.'],['Support & Maintenance','Monitoring, backup, updates, and ongoing technical care.']],th:[['ซอฟต์แวร์เฉพาะธุรกิจ','เว็บแอปและระบบภายในที่ออกแบบตามวิธีทำงานของทีมคุณ'],['ระบบอัตโนมัติทางธุรกิจ','ลดงานซ้ำและเปลี่ยนขั้นตอน manual ให้เป็น workflow ที่ชัดเจน'],['โซลูชันเว็บ','เว็บไซต์องค์กร พอร์ทัล และบริการออนไลน์ที่มีเป้าหมายชัดเจน'],['เชื่อมต่อระบบ','เชื่อม API ฐานข้อมูล เครื่องมือเดิม และข้อมูลหน้างาน'],['ดูแลและบำรุงรักษา','Monitoring, backup, update และดูแลด้านเทคนิคอย่างต่อเนื่อง']]};
const process={en:[['01','Understand'],['02','Define'],['03','Design'],['04','Build'],['05','Support']],th:[['01','เข้าใจ'],['02','กำหนด'],['03','ออกแบบ'],['04','พัฒนา'],['05','ดูแล']]};

function Mark(){return <a href="#home" className="brand" aria-label="CeroSoft"><Image src={logo} alt="" width={42} height={42}/><b>Cero<span>Soft</span></b></a>}
function Tag({children}:{children:React.ReactNode}){return <span className="tag"><i/>{children}</span>}
function Navbar({lang,setLang}:{lang:Lang,setLang:(l:Lang)=>void}){const[open,setOpen]=useState(false);const c=copy[lang];return <header className="navbar"><div className="nav-inner"><Mark/><nav className="desktop-nav">{['home','problem','solutions','portfolio','about','contact'].map((id,i)=><a key={id} href={`#${id}`}>{c.nav[i]}</a>)}</nav><button className="lang" onClick={()=>setLang(lang==='en'?'th':'en')} aria-label="Switch language"><Languages/> {lang==='en'?'TH':'EN'}</button><a className="cta" href="#contact">{c.talk}<ArrowRight/></a><button className="menu" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button></div><nav className={`mobile-nav ${open?'open':''}`}>{c.nav.map((x,i)=><a key={x} href={`#${['home','problem','solutions','portfolio','about','contact'][i]}`} onClick={()=>setOpen(false)}>{x}<ChevronRight/></a>)}</nav></header>}
function Hero({lang}:{lang:Lang}){const c=copy[lang];return <section id="home" className="hero"><div className="wire w1"/><div className="wire w2"/><div className="container hero-grid"><div><Tag>{c.heroTag}</Tag><h1>{c.heroTitle}</h1><p>{c.heroText}</p><div className="hero-actions"><a className="button" href="#portfolio">{c.explore}<ArrowDownRight/></a><a className="text-link light" href="#contact">{c.talk}<ArrowRight/></a></div></div><div className="hero-system" aria-hidden="true"><div className="zero-ring"><span>0</span></div><div className="system-line"><i/><i/><i/><i/></div><div className="system-label"><small>ZERO</small><b>UNDERSTAND</b><b>DESIGN</b><b>BUILD</b><small>SOLUTION</small></div></div></div><div className="container hero-foot">{c.proof.map(x=><span key={x}>{x}</span>)}<b>01 — 00</b></div></section>}
function Problem({lang}:{lang:Lang}){const c=copy[lang];return <section id="problem" className="section problem"><div className="container"><div className="split-head"><div><Tag>{c.problemTag}</Tag><h2>{c.problemTitle}</h2></div><div><p className="large">{c.problemText}</p><p>{c.problemClose}</p></div></div><div className="problem-grid">{c.problems.map(([n,t,p])=><article key={n}><small>{n}</small><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>}
function Solutions({lang}:{lang:Lang}){const c=copy[lang];return <section id="solutions" className="section solutions"><div className="container"><div className="split-head"><div><Tag>{c.solutionsTag}</Tag><h2>{c.solutionsTitle}</h2></div><p className="large">{c.solutionsText}</p></div><div className="service-list">{serviceText[lang].map(([t,p],i)=>{const Icon=services[i];return <article key={t}><span>0{i+1}</span><Icon/><h3>{t}</h3><p>{p}</p><ArrowDownRight/></article>})}</div></div></section>}
function Portfolio({lang}:{lang:Lang}){const c=copy[lang];return <section id="portfolio" className="section portfolio"><div className="container"><div className="portfolio-head"><div><Tag>{c.portfolioTag}</Tag><h2>{c.portfolioTitle}</h2><h3>{c.portfolioSub}</h3></div><div><p className="large">{c.portfolioText}</p><div className="pills"><span><i/>{c.live}</span><span>{c.resident}</span><span>{c.management}</span></div></div></div><div className="product-stage"><div className="stage-copy"><small>CONDOMATE / PUNNA RESIDENCE 5</small><h3>{lang==='en'?'One operational system. Two clear experiences.':'หนึ่งระบบปฏิบัติการ สองประสบการณ์ที่ชัดเจน'}</h3><p>{c.portfolioNote}</p><a className="button inverted" href="#contact">{c.portfolioCta}<ArrowRight/></a></div><div className="phones"><div className="phone back"><Image src="/portfolio/condomate-access.jpg" alt="CondoMate access selection" width={946} height={1771} sizes="(max-width: 700px) 42vw, 280px"/></div><div className="phone front"><Image src="/portfolio/condomate-resident-dashboard.jpg" alt="CondoMate resident dashboard" width={932} height={1750} sizes="(max-width: 700px) 48vw, 310px"/></div></div></div><div className="gallery">{[['/portfolio/condomate-resident-dashboard.jpg'],['/portfolio/condomate-maintenance.jpg'],['/portfolio/condomate-booking.jpg']].map((img,i)=><article key={img[0]}><div><Image src={img[0]} alt={c.gallery[i][0]} width={946} height={1771} sizes="(max-width: 700px) 80vw, 340px"/></div><small>0{i+1}</small><h3>{c.gallery[i][0]}</h3><p>{c.gallery[i][1]}</p></article>)}</div></div></section>}
function Process({lang}:{lang:Lang}){const c=copy[lang];return <section className="section process-section"><div className="container"><div className="process-head"><div><Tag>{c.processTag}</Tag><h2>{c.processTitle}</h2></div><p className="large">{c.processText}</p></div><div className="process-line">{process[lang].map(([n,t])=><article key={n}><span>{n}</span><i/><h3>{t}</h3></article>)}</div></div></section>}
function About({lang}:{lang:Lang}){const c=copy[lang];return <section id="about" className="section about"><div className="container"><Tag>{c.aboutTag}</Tag><div className="about-grid"><h2>{c.aboutTitle}</h2><p className="large">{c.aboutText}</p></div><div className="manifest"><article><small>01 / MISSION</small><p>{c.mission}</p></article><article><small>02 / VISION</small><p>{c.vision}</p></article><article className="values"><small>03 / VALUES</small><p>Simple · Practical · Reliable · Adaptable · Transparent</p></article></div></div></section>}
function Legacy({lang}:{lang:Lang}){const c=copy[lang];return <section className="section legacy"><div className="container legacy-grid"><Tag>{c.legacyTag}</Tag><h2>{c.legacyTitle}</h2><div><p className="large">{c.legacyText}</p><a className="text-link" href="#contact">{c.legacyCta}<ArrowRight/></a></div></div></section>}
function Contact({lang}:{lang:Lang}){const c=copy[lang];const[status,setStatus]=useState('');const[sending,setSending]=useState(false);const submit=async(e:SyntheticEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;if(!form.checkValidity()){form.reportValidity();return}setSending(true);setStatus('');try{const data=Object.fromEntries(new FormData(form).entries());const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,language:lang})});if(!response.ok)throw new Error('send failed');setStatus(c.success);form.reset()}catch{setStatus(lang==='th'?'ส่งข้อความไม่สำเร็จ กรุณาลองอีกครั้งหรือติดต่อทางอีเมล':'Message could not be sent. Please try again or contact us by email.')}finally{setSending(false)}};return <section id="contact" className="section contact"><div className="container contact-grid"><div><Tag>{c.contactTag}</Tag><h2>{c.contactTitle}</h2><p className="large">{c.contactText}</p><div className="next"><Check/><span>{c.next}</span></div></div><form onSubmit={submit} noValidate><input className="hp" type="text" name="website" tabIndex={-1} autoComplete="off"/><div className="field-row"><label>{c.fields[0]}<input required name="name" autoComplete="name" maxLength={100}/></label><label>{c.fields[1]}<input required name="company" autoComplete="organization" maxLength={150}/></label></div><div className="field-row"><label>{c.fields[2]}<input required type="email" name="email" autoComplete="email" maxLength={200}/></label><label>{c.fields[3]}<input type="tel" name="phone" autoComplete="tel" maxLength={50}/></label></div><label>{c.fields[4]}<select required name="interest" defaultValue=""><option value="" disabled>—</option><option>Custom Software</option><option>Business Automation</option><option>System Integration</option><option>Support & Maintenance</option></select></label><label>{c.fields[5]}<textarea required name="message" rows={5} maxLength={3000}/></label><button className="button" type="submit" disabled={sending}>{sending?(lang==='th'?'กำลังส่ง…':'Sending…'):c.send}<ArrowRight/></button><output>{status}</output></form></div></section>}
function Footer({lang}:{lang:Lang}){const c=copy[lang];return <footer><div className="container footer-grid"><div><Mark/><p>From Zero to Solution.</p></div><div><small>EXPLORE</small>{c.nav.slice(1).map((x,i)=><a key={x} href={`#${['problem','solutions','portfolio','about','contact'][i]}`}>{x}</a>)}</div><div><small>ONLINE</small><a href="https://cerosoft.net">cerosoft.net</a><p>{c.footer}</p></div></div><div className="container copyright">© {new Date().getFullYear()} CeroSoft <span>Bangkok, Thailand</span></div></footer>}
export default function CeroSoftSite(){const[lang,setLang]=useState<Lang>(()=>{if(typeof window==='undefined')return'en';const saved=localStorage.getItem('cerosoft-lang');return saved==='th'?'th':'en'});const change=(l:Lang)=>{setLang(l);localStorage.setItem('cerosoft-lang',l)};return <div lang={lang}><Navbar lang={lang} setLang={change}/><main><Hero lang={lang}/><Problem lang={lang}/><Solutions lang={lang}/><Portfolio lang={lang}/><Process lang={lang}/><About lang={lang}/><Legacy lang={lang}/><Contact lang={lang}/></main><Footer lang={lang}/></div>}
